In intial days Matplotlib was present to perform numeric calculation.

There is no numeric calculations happens in the python

After that python researchers introducd numpy(numeric python) module to perform all the mathematical operation.

NUmpy performm well on the matrix and the array 

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
# Convert list into array
arr=np.array(l)

In [4]:
type(arr)   # ndarray = n- dimensional array

numpy.ndarray

In [5]:
# Another way of creating array
arr1=np.asarray(l)

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.ndim   #Tells the dimension of the array

1

In [8]:
l2=[[1,2,3],
   [4,5,6]]

In [9]:
arr2=np.asarray(l2)

In [10]:
type(arr2)

numpy.ndarray

In [11]:
arr2.ndim       #Tells the dimension of the array

2

#### Visualize the 2-D array

#### Array can ne have a 1 dimension or more dimension
#### But matrix can't be a 1 dimensiion it will always be 2 or more dimensions
#### Matrix is a subclass of array in numpy

In [12]:
l

[1, 2, 3, 4, 5]

In [13]:
# Matrix function will convert its argument into minimum 2-Dimensions
mat=np.matrix(l)

In [14]:
mat

matrix([[1, 2, 3, 4, 5]])

In [15]:
type(mat)

numpy.matrix

In [16]:
mat.ndim

2

#### Observation: Asanyarray function will convert its argument into a array if is not in a form of array But it is already is in a from of a array it will remain unchanged.

In [17]:
#Now
np.asanyarray(l)    #it does change into array

array([1, 2, 3, 4, 5])

In [18]:
np.asanyarray(mat)   # matrix is subclass of array .thatswhy it does not change into array(remain same)

matrix([[1, 2, 3, 4, 5]])

#### Shallow copy in array

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a=arr2    # Reassign into another variable

In [21]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a[1][0]=26    # Manipulate the copy

In [23]:
a

array([[ 1,  2,  3],
       [26,  5,  6]])

In [24]:
arr2   #The real array is also get changed

array([[ 1,  2,  3],
       [26,  5,  6]])

#### Deep copy
using copy function

copy function :It stores the copy of the array inside a new memory location.That's why the change in one array will not affect the other array 

In [25]:
arr2

array([[ 1,  2,  3],
       [26,  5,  6]])

In [26]:
b=np.copy(arr2)     # Manipulate the copy

In [27]:
b

array([[ 1,  2,  3],
       [26,  5,  6]])

In [28]:
b[0][2]=15

In [29]:
b

array([[ 1,  2, 15],
       [26,  5,  6]])

In [30]:
arr2   # The original array will not get affected

array([[ 1,  2,  3],
       [26,  5,  6]])

#### Different functions in the numpy ( different ways to create array as datatypes )

In [31]:
# Fromfunction: It takes a function as an argument and based on that function it generates the datasets.
np.fromfunction(lambda i,j: i==j,(3,3))   # variables and the shape of the array (3,3)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [32]:
np.fromfunction(lambda i,j: i+j,(3,3)) 

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [33]:
# Generator 
type1=list((i*i for i in range(5)))

In [34]:
type1

[0, 1, 4, 9, 16]

In [35]:
type(type1)

list

We can also write generator in the numpy as well

using from iter function

In [36]:
iterable=(i*i for i in range(5))

In [37]:
np.fromiter(iterable,int)   #It takes the datasets and the datatype

array([ 0,  1,  4,  9, 16])

In [51]:
np.empty((3,3))   #This will give very small values to the array

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

#### Observation : The generation gives the list as an output but fromiter method is used to gives out a array

In [39]:
# fromstring function: it takes the string as argument and then create the array datasets out of it .

In [40]:
np.fromstring("23 45 56 67",sep=" ")    # It takes stirng and a seperator 

array([23., 45., 56., 67.])

In [41]:
np.fromstring("23,45,56,67",sep=",")   #It return the array datasets

array([23., 45., 56., 67.])

#### Query : How can we make 2-D array out of this functions

####  Some other numpy function

In [42]:
arr2

array([[ 1,  2,  3],
       [26,  5,  6]])

In [43]:
arr2.size   #IT gives the total no of element persent in the array

6

In [44]:
arr1

array([1, 2, 3, 4, 5])

In [45]:
arr1.size

5

In [46]:
arr1.shape    #It tells the no of row and columns 

(5,)

In [47]:
arr2.shape  #It tells the no of row and columns 

(2, 3)

In [48]:
arr1.dtype   # Type of datatype of the element of the array

dtype('int64')

In [49]:
arr2.dtype   # Type of datatype of the element of the array

dtype('int64')